### ISSUE TITLE
Unable to press identicons for more info

### ISSUE THREAD

**Issue by krisnaer** [trustlines-network/feedback#41] opened 2018-03-15 13:20 UTC
### Basic information:

* OS (Android / iOS / both): Andoir
* Version: 7.00

### Issue description:
When pressing the identicon of trustlines users, I am unable to see more information of the user. This prevents me from adding new contacts

### Screenshots or mock-ups
![cant press identicons for info](https://user-images.githubusercontent.com/29100596/37465642-028468fc-285c-11e8-8294-e19442b2ec18.png)
![screenshot_20180313-094915](https://user-images.githubusercontent.com/29100596/37465643-037de684-285c-11e8-8ac7-813042d535f3.png)

**Comment by Kisgus** [comment] 2018-03-15 14:43
@krisnaer I just tested this with my Sony Expedia phone, and Chris just tested it on his Xiaomi 5s and it works for both of us + on my iOS. Could you please provide your exact phone model for us to trouble shoot?

**Comment by Kisgus** [comment] 2018-04-04 09:59
Closing as I cannot reproduce the bug on any other Android or iOS phones.

**Closed by Kisgus** 2018-04-04 09:59 UTC
Labels: bug
